version: '3.9'
services:
  database:
    image: postgres:17
    container_name: postgres-dev
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: full_stack_app
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - nest-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: nest-app-dev
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://root:root@database:5432/full_stack_app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - database
    networks:
      - nest-network

volumes:
  postgres-data:

networks:
  nest-network: